import { Injectable } from '@nestjs/common';

export interface ApplicationTimeline {
  stage: string;
  date: string;
  desc: string;
  status: 'completed' | 'active' | 'pending';
}

export interface Application {
  id: number;
  opportunityId: number;
  candidateId: number;
  candidateName: string;
  branch?: string;
  cgpa?: number;
  title: string;
  company: string;
  type: string;
  status: string;
  appliedDate: string;
  hasReferral: boolean;
  currentStageIndex: number;
  timeline: ApplicationTimeline[];
  interviewDate?: string;
  remarks?: string;
  resumeFile?: string;
  initials?: string;
  collegeId?: number;
  rounds?: {
    resume?: string;
    assessment?: string;
    technical?: string;
    hr?: string;
  };
}


@Injectable()
export class ApplicationsRepository {
  private applications: Application[] = [
    { id: 1, opportunityId: 1, candidateId: 1, candidateName: 'Shameer Basha Shaik', branch: 'Computer Science', cgpa: 8.7, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-time', status: 'Interview', appliedDate: '2026-02-15', hasReferral: true, currentStageIndex: 4, initials: 'SB', rounds: { resume: 'Pass', assessment: 'Pass', technical: 'Scheduled', hr: 'Scheduled' }, timeline: [{ stage: 'Applied', date: '2026-02-15', desc: 'Submitted', status: 'completed' }, { stage: 'Shortlisted', date: '2026-02-20', desc: 'Reviewed', status: 'completed' }, { stage: 'Assessment', date: '2026-02-24', desc: 'Score: 85/100', status: 'completed' }, { stage: 'Interview', date: '2026-02-28', desc: 'Round 1 scheduled', status: 'active' }] },
    { id: 2, opportunityId: 2, candidateId: 1, candidateName: 'Shameer Basha Shaik', branch: 'Computer Science', cgpa: 8.7, title: 'Data Analyst Intern', company: 'Analytics Hub', type: 'Internship', status: 'Shortlisted', appliedDate: '2026-02-18', hasReferral: false, currentStageIndex: 2, initials: 'SB', rounds: { resume: 'Pass', assessment: 'Scheduled', technical: 'Scheduled', hr: 'Scheduled' }, timeline: [{ stage: 'Applied', date: '2026-02-18', desc: 'Submitted', status: 'completed' }, { stage: 'Shortlisted', date: '2026-02-25', desc: 'Matched', status: 'completed' }, { stage: 'Assessment', date: '2026-03-01', desc: 'Pending link', status: 'active' }] },
    { id: 3, opportunityId: 3, candidateId: 1, candidateName: 'Shameer Basha Shaik', branch: 'Computer Science', cgpa: 8.7, title: 'Full Stack Developer', company: 'InnovateTech', type: 'Full-Time', status: 'Rejected', appliedDate: '2026-01-10', hasReferral: false, currentStageIndex: 2, initials: 'SB', rounds: { resume: 'Fail', assessment: 'Scheduled', technical: 'Scheduled', hr: 'Scheduled' }, timeline: [{ stage: 'Applied', date: '2026-01-10', desc: 'Submitted', status: 'completed' }, { stage: 'Rejected', date: '2026-01-25', desc: 'Moving forward with others', status: 'completed' }] },
    { id: 4, opportunityId: 5, candidateId: 1, candidateName: 'Shameer Basha Shaik', branch: 'Computer Science', cgpa: 8.7, title: 'Backend Engineer Intern', company: 'CloudBase Inc', type: 'Internship', status: 'Offer', appliedDate: '2026-01-05', hasReferral: true, currentStageIndex: 4, initials: 'SB', rounds: { resume: 'Pass', assessment: 'Pass', technical: 'Pass', hr: 'Pass' }, timeline: [{ stage: 'Applied', date: '2026-01-05', desc: 'Submitted', status: 'completed' }, { stage: 'Shortlisted', date: '2026-01-15', desc: 'Selected directly', status: 'completed' }, { stage: 'Interview', date: '2026-01-28', desc: 'Cleared', status: 'completed' }, { stage: 'Offer', date: '2026-02-05', desc: 'Accept by Feb 15th', status: 'completed' }] },
    { id: 5, opportunityId: 8, candidateId: 1, candidateName: 'Shameer Basha Shaik', branch: 'Computer Science', cgpa: 8.7, title: 'Frontend Developer', company: 'WebFlow Media', type: 'Full-Time', status: 'Applied', appliedDate: '2026-03-10', hasReferral: false, currentStageIndex: 1, initials: 'SB', rounds: { resume: 'Pass', assessment: 'Scheduled', technical: 'Scheduled', hr: 'Scheduled' }, timeline: [{ stage: 'Applied', date: '2026-03-10', desc: 'Submitted', status: 'completed' }, { stage: 'Reviewing', date: '-', desc: 'Pending', status: 'active' }] },
    // Recruiter-visible applications for opportunity 1
    { id: 6, opportunityId: 1, candidateId: 2, candidateName: 'Arjun Sharma', branch: 'Computer Science', cgpa: 9.7, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Interview', appliedDate: '2026-02-18', hasReferral: true, currentStageIndex: 3, initials: 'AS', resumeFile: 'arjun_resume_v2.pdf', rounds: { resume: 'Pass', assessment: 'Pass', technical: 'Scheduled', hr: 'Scheduled' }, timeline: [{ stage: 'Applied', date: '2026-02-18', desc: 'Submitted', status: 'completed' }, { stage: 'Shortlisted', date: '2026-02-22', desc: 'Reviewed', status: 'completed' }, { stage: 'Interview', date: '2026-02-28', desc: 'Round 1 scheduled', status: 'active' }] },
    { id: 7, opportunityId: 1, candidateId: 3, candidateName: 'Priya Patel', branch: 'Electronics', cgpa: 7.9, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Applied', appliedDate: '2026-03-01', hasReferral: false, currentStageIndex: 1, initials: 'PP', resumeFile: 'priya_cv.pdf', rounds: { resume: 'Pass', assessment: 'Scheduled', technical: 'Scheduled', hr: 'Scheduled' }, timeline: [{ stage: 'Applied', date: '2026-03-01', desc: 'Submitted', status: 'completed' }] },
    { id: 8, opportunityId: 1, candidateId: 4, candidateName: 'Rahul Mehta', branch: 'Computer Science', cgpa: 9.1, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Offered', appliedDate: '2026-01-25', hasReferral: true, currentStageIndex: 4, initials: 'RM', resumeFile: 'rahul_final_resume.pdf', rounds: { resume: 'Pass', assessment: 'Pass', technical: 'Pass', hr: 'Pass' }, timeline: [{ stage: 'Applied', date: '2026-01-25', desc: 'Submitted', status: 'completed' }, { stage: 'Shortlisted', date: '2026-01-30', desc: 'Reviewed', status: 'completed' }, { stage: 'Technical', date: '2026-02-05', desc: 'Passed', status: 'completed' }, { stage: 'Offered', date: '2026-02-15', desc: 'Offer extended', status: 'completed' }] },
    { id: 9, opportunityId: 2, candidateId: 5, candidateName: 'Sneha Reddy', branch: 'IT', cgpa: 8.5, title: 'Data Analyst Intern', company: 'Analytics Hub', type: 'Internship', status: 'Assessment', appliedDate: '2026-03-10', hasReferral: false, currentStageIndex: 2, initials: 'SR', resumeFile: 'sneha_resume.pdf', rounds: { resume: 'Pass', assessment: 'Scheduled', technical: 'Scheduled', hr: 'Scheduled' }, timeline: [{ stage: 'Applied', date: '2026-03-10', desc: 'Submitted', status: 'completed' }, { stage: 'Assessment', date: '2026-03-15', desc: 'Scheduled', status: 'active' }] },
    { id: 10, opportunityId: 1, candidateId: 6, candidateName: 'Vikram Singh', branch: 'Mechanical', cgpa: 8.2, title: 'Production Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Rejected', appliedDate: '2026-02-10', hasReferral: true, currentStageIndex: 2, initials: 'VS', resumeFile: 'vikram_mech_resume.pdf', rounds: { resume: 'Fail', assessment: 'Scheduled', technical: 'Scheduled', hr: 'Scheduled' }, timeline: [{ stage: 'Applied', date: '2026-02-10', desc: 'Submitted', status: 'completed' }, { stage: 'Rejected', date: '2026-02-18', desc: 'Resume did not pass', status: 'completed' }] },
    // ── Bulk placement season applications (added for statistics) ─────────────
    { id: 11, opportunityId: 1, candidateId: 10, candidateName: 'Arjun Kumar', branch: 'Computer Science', cgpa: 8.9, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Offered', appliedDate: '2025-09-05', hasReferral: false, currentStageIndex: 1, initials: 'AK', timeline: [{ stage: 'Applied', date: '2025-09-05', desc: 'Submitted', status: 'completed' }] },
    { id: 12, opportunityId: 3, candidateId: 11, candidateName: 'Deepika Nair', branch: 'Computer Science', cgpa: 8.2, title: 'Full Stack Developer', company: 'InnovateTech', type: 'Full-Time', status: 'Offered', appliedDate: '2025-09-12', hasReferral: false, currentStageIndex: 1, initials: 'DN', timeline: [{ stage: 'Applied', date: '2025-09-12', desc: 'Submitted', status: 'completed' }] },
    { id: 13, opportunityId: 4, candidateId: 12, candidateName: 'Farhan Ahmed', branch: 'Computer Science', cgpa: 7.8, title: 'ML Engineer', company: 'AI Dynamics', type: 'Full-Time', status: 'Offered', appliedDate: '2025-09-18', hasReferral: false, currentStageIndex: 1, initials: 'FA', timeline: [{ stage: 'Applied', date: '2025-09-18', desc: 'Submitted', status: 'completed' }] },
    { id: 14, opportunityId: 1, candidateId: 13, candidateName: 'Gita Rao', branch: 'Computer Science', cgpa: 9.3, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Offered', appliedDate: '2025-09-22', hasReferral: false, currentStageIndex: 1, initials: 'GR', timeline: [{ stage: 'Applied', date: '2025-09-22', desc: 'Submitted', status: 'completed' }] },
    { id: 15, opportunityId: 9, candidateId: 14, candidateName: 'Harsh Verma', branch: 'Computer Science', cgpa: 8.5, title: 'Backend Engineer', company: 'FinTech Corp', type: 'Full-Time', status: 'Offered', appliedDate: '2025-10-03', hasReferral: false, currentStageIndex: 1, initials: 'HV', timeline: [{ stage: 'Applied', date: '2025-10-03', desc: 'Submitted', status: 'completed' }] },
    { id: 16, opportunityId: 3, candidateId: 15, candidateName: 'Indira Pillai', branch: 'Computer Science', cgpa: 8, title: 'Full Stack Developer', company: 'InnovateTech', type: 'Full-Time', status: 'Offered', appliedDate: '2025-10-08', hasReferral: false, currentStageIndex: 1, initials: 'IP', timeline: [{ stage: 'Applied', date: '2025-10-08', desc: 'Submitted', status: 'completed' }] },
    { id: 17, opportunityId: 12, candidateId: 16, candidateName: 'Jatin Malhotra', branch: 'Computer Science', cgpa: 7.5, title: 'Data Scientist', company: 'DataMinds', type: 'Full-Time', status: 'Rejected', appliedDate: '2025-10-14', hasReferral: false, currentStageIndex: 1, initials: 'JM', timeline: [{ stage: 'Applied', date: '2025-10-14', desc: 'Submitted', status: 'completed' }] },
    { id: 18, opportunityId: 1, candidateId: 17, candidateName: 'Komal Shah', branch: 'Computer Science', cgpa: 8.7, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Offered', appliedDate: '2025-10-20', hasReferral: false, currentStageIndex: 1, initials: 'KS', timeline: [{ stage: 'Applied', date: '2025-10-20', desc: 'Submitted', status: 'completed' }] },
    { id: 19, opportunityId: 4, candidateId: 18, candidateName: 'Lokesh Gupta', branch: 'Computer Science', cgpa: 7.2, title: 'ML Engineer', company: 'AI Dynamics', type: 'Full-Time', status: 'Rejected', appliedDate: '2025-10-28', hasReferral: false, currentStageIndex: 1, initials: 'LG', timeline: [{ stage: 'Applied', date: '2025-10-28', desc: 'Submitted', status: 'completed' }] },
    { id: 20, opportunityId: 9, candidateId: 19, candidateName: 'Meera Joshi', branch: 'Computer Science', cgpa: 9, title: 'Backend Engineer', company: 'FinTech Corp', type: 'Full-Time', status: 'Offered', appliedDate: '2025-11-02', hasReferral: false, currentStageIndex: 1, initials: 'MJ', timeline: [{ stage: 'Applied', date: '2025-11-02', desc: 'Submitted', status: 'completed' }] },
    { id: 21, opportunityId: 3, candidateId: 20, candidateName: 'Naman Agarwal', branch: 'Computer Science', cgpa: 8.3, title: 'Full Stack Developer', company: 'InnovateTech', type: 'Full-Time', status: 'Offered', appliedDate: '2025-11-08', hasReferral: false, currentStageIndex: 1, initials: 'NA', timeline: [{ stage: 'Applied', date: '2025-11-08', desc: 'Submitted', status: 'completed' }] },
    { id: 22, opportunityId: 11, candidateId: 21, candidateName: 'Preethi Krishnan', branch: 'Computer Science', cgpa: 9.1, title: 'Cloud Architect', company: 'Skyline Cloud', type: 'Full-Time', status: 'Offered', appliedDate: '2025-11-14', hasReferral: false, currentStageIndex: 1, initials: 'PK', timeline: [{ stage: 'Applied', date: '2025-11-14', desc: 'Submitted', status: 'completed' }] },
    { id: 23, opportunityId: 1, candidateId: 22, candidateName: 'Rohit Tripathi', branch: 'Computer Science', cgpa: 8.4, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Offered', appliedDate: '2025-11-20', hasReferral: false, currentStageIndex: 1, initials: 'RT', timeline: [{ stage: 'Applied', date: '2025-11-20', desc: 'Submitted', status: 'completed' }] },
    { id: 24, opportunityId: 12, candidateId: 23, candidateName: 'Shruti Kapur', branch: 'Computer Science', cgpa: 8.8, title: 'Data Scientist', company: 'DataMinds', type: 'Full-Time', status: 'Offered', appliedDate: '2025-11-25', hasReferral: false, currentStageIndex: 1, initials: 'SK', timeline: [{ stage: 'Applied', date: '2025-11-25', desc: 'Submitted', status: 'completed' }] },
    { id: 25, opportunityId: 8, candidateId: 24, candidateName: 'Tarun Bhat', branch: 'Computer Science', cgpa: 7.6, title: 'Frontend Developer', company: 'WebFlow Media', type: 'Full-Time', status: 'Interview', appliedDate: '2025-12-03', hasReferral: false, currentStageIndex: 1, initials: 'TB', timeline: [{ stage: 'Applied', date: '2025-12-03', desc: 'Submitted', status: 'completed' }] },
    { id: 26, opportunityId: 3, candidateId: 25, candidateName: 'Usha Menon', branch: 'Computer Science', cgpa: 8.1, title: 'Full Stack Developer', company: 'InnovateTech', type: 'Full-Time', status: 'Offered', appliedDate: '2025-12-08', hasReferral: false, currentStageIndex: 1, initials: 'UM', timeline: [{ stage: 'Applied', date: '2025-12-08', desc: 'Submitted', status: 'completed' }] },
    { id: 27, opportunityId: 9, candidateId: 26, candidateName: 'Vijay Sinha', branch: 'Computer Science', cgpa: 7.7, title: 'Backend Engineer', company: 'FinTech Corp', type: 'Full-Time', status: 'Offered', appliedDate: '2025-12-15', hasReferral: false, currentStageIndex: 1, initials: 'VS', timeline: [{ stage: 'Applied', date: '2025-12-15', desc: 'Submitted', status: 'completed' }] },
    { id: 28, opportunityId: 1, candidateId: 27, candidateName: 'Wasim Khan', branch: 'Computer Science', cgpa: 8.2, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Offered', appliedDate: '2025-12-20', hasReferral: false, currentStageIndex: 1, initials: 'WK', timeline: [{ stage: 'Applied', date: '2025-12-20', desc: 'Submitted', status: 'completed' }] },
    { id: 29, opportunityId: 4, candidateId: 28, candidateName: 'Xena Roy', branch: 'Computer Science', cgpa: 9.2, title: 'ML Engineer', company: 'AI Dynamics', type: 'Full-Time', status: 'Offered', appliedDate: '2026-01-06', hasReferral: false, currentStageIndex: 1, initials: 'XR', timeline: [{ stage: 'Applied', date: '2026-01-06', desc: 'Submitted', status: 'completed' }] },
    { id: 30, opportunityId: 11, candidateId: 29, candidateName: 'Yash Pandey', branch: 'Computer Science', cgpa: 8.6, title: 'Cloud Architect', company: 'Skyline Cloud', type: 'Full-Time', status: 'Offered', appliedDate: '2026-01-10', hasReferral: false, currentStageIndex: 1, initials: 'YP', timeline: [{ stage: 'Applied', date: '2026-01-10', desc: 'Submitted', status: 'completed' }] },
    { id: 31, opportunityId: 12, candidateId: 30, candidateName: 'Zoya Ansari', branch: 'Computer Science', cgpa: 7.9, title: 'Data Scientist', company: 'DataMinds', type: 'Full-Time', status: 'Shortlisted', appliedDate: '2026-01-15', hasReferral: false, currentStageIndex: 1, initials: 'ZA', timeline: [{ stage: 'Applied', date: '2026-01-15', desc: 'Submitted', status: 'completed' }] },
    { id: 32, opportunityId: 1, candidateId: 31, candidateName: 'Nikhil Reddy', branch: 'Electronics', cgpa: 8.4, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Offered', appliedDate: '2025-09-08', hasReferral: false, currentStageIndex: 1, initials: 'NR', timeline: [{ stage: 'Applied', date: '2025-09-08', desc: 'Submitted', status: 'completed' }] },
    { id: 33, opportunityId: 13, candidateId: 32, candidateName: 'Pooja Sharma', branch: 'Electronics', cgpa: 8.6, title: 'Hardware Intern', company: 'Silicon Devices', type: 'Internship', status: 'Offered', appliedDate: '2025-09-15', hasReferral: false, currentStageIndex: 1, initials: 'PS', timeline: [{ stage: 'Applied', date: '2025-09-15', desc: 'Submitted', status: 'completed' }] },
    { id: 34, opportunityId: 1, candidateId: 33, candidateName: 'Ravi Krishnan', branch: 'Electronics', cgpa: 8.1, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Offered', appliedDate: '2025-09-24', hasReferral: false, currentStageIndex: 1, initials: 'RK', timeline: [{ stage: 'Applied', date: '2025-09-24', desc: 'Submitted', status: 'completed' }] },
    { id: 35, opportunityId: 4, candidateId: 34, candidateName: 'Sana Mirza', branch: 'Electronics', cgpa: 8.8, title: 'ML Engineer', company: 'AI Dynamics', type: 'Full-Time', status: 'Offered', appliedDate: '2025-10-05', hasReferral: false, currentStageIndex: 1, initials: 'SM', timeline: [{ stage: 'Applied', date: '2025-10-05', desc: 'Submitted', status: 'completed' }] },
    { id: 36, opportunityId: 13, candidateId: 35, candidateName: 'Tarun Mishra', branch: 'Electronics', cgpa: 7.5, title: 'Hardware Intern', company: 'Silicon Devices', type: 'Internship', status: 'Rejected', appliedDate: '2025-10-12', hasReferral: false, currentStageIndex: 1, initials: 'TM', timeline: [{ stage: 'Applied', date: '2025-10-12', desc: 'Submitted', status: 'completed' }] },
    { id: 37, opportunityId: 11, candidateId: 36, candidateName: 'Uma Devi', branch: 'Electronics', cgpa: 8.3, title: 'Cloud Architect', company: 'Skyline Cloud', type: 'Full-Time', status: 'Offered', appliedDate: '2025-10-22', hasReferral: false, currentStageIndex: 1, initials: 'UD', timeline: [{ stage: 'Applied', date: '2025-10-22', desc: 'Submitted', status: 'completed' }] },
    { id: 38, opportunityId: 1, candidateId: 37, candidateName: 'Vikram Rao', branch: 'Electronics', cgpa: 7.8, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Offered', appliedDate: '2025-11-03', hasReferral: false, currentStageIndex: 1, initials: 'VR', timeline: [{ stage: 'Applied', date: '2025-11-03', desc: 'Submitted', status: 'completed' }] },
    { id: 39, opportunityId: 13, candidateId: 38, candidateName: 'Waqar Ali', branch: 'Electronics', cgpa: 8, title: 'Hardware Intern', company: 'Silicon Devices', type: 'Internship', status: 'Offered', appliedDate: '2025-11-10', hasReferral: false, currentStageIndex: 1, initials: 'WA', timeline: [{ stage: 'Applied', date: '2025-11-10', desc: 'Submitted', status: 'completed' }] },
    { id: 40, opportunityId: 3, candidateId: 39, candidateName: 'Yogesh Patil', branch: 'Electronics', cgpa: 8.5, title: 'Full Stack Developer', company: 'InnovateTech', type: 'Full-Time', status: 'Offered', appliedDate: '2025-11-18', hasReferral: false, currentStageIndex: 1, initials: 'YP', timeline: [{ stage: 'Applied', date: '2025-11-18', desc: 'Submitted', status: 'completed' }] },
    { id: 41, opportunityId: 4, candidateId: 40, candidateName: 'Abhilash Nair', branch: 'Electronics', cgpa: 8.7, title: 'ML Engineer', company: 'AI Dynamics', type: 'Full-Time', status: 'Offered', appliedDate: '2025-12-01', hasReferral: false, currentStageIndex: 1, initials: 'AN', timeline: [{ stage: 'Applied', date: '2025-12-01', desc: 'Submitted', status: 'completed' }] },
    { id: 42, opportunityId: 13, candidateId: 41, candidateName: 'Bhumika Jain', branch: 'Electronics', cgpa: 8.2, title: 'Hardware Intern', company: 'Silicon Devices', type: 'Internship', status: 'Offered', appliedDate: '2025-12-10', hasReferral: false, currentStageIndex: 1, initials: 'BJ', timeline: [{ stage: 'Applied', date: '2025-12-10', desc: 'Submitted', status: 'completed' }] },
    { id: 43, opportunityId: 1, candidateId: 42, candidateName: 'Chetan Sharma', branch: 'Electronics', cgpa: 7.6, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Rejected', appliedDate: '2025-12-18', hasReferral: false, currentStageIndex: 1, initials: 'CS', timeline: [{ stage: 'Applied', date: '2025-12-18', desc: 'Submitted', status: 'completed' }] },
    { id: 44, opportunityId: 11, candidateId: 43, candidateName: 'Dhruv Kapoor', branch: 'Electronics', cgpa: 8.9, title: 'Cloud Architect', company: 'Skyline Cloud', type: 'Full-Time', status: 'Offered', appliedDate: '2026-01-08', hasReferral: false, currentStageIndex: 1, initials: 'DK', timeline: [{ stage: 'Applied', date: '2026-01-08', desc: 'Submitted', status: 'completed' }] },
    { id: 45, opportunityId: 3, candidateId: 44, candidateName: 'Elina Roy', branch: 'Electronics', cgpa: 8.4, title: 'Full Stack Developer', company: 'InnovateTech', type: 'Full-Time', status: 'Offered', appliedDate: '2026-01-14', hasReferral: false, currentStageIndex: 1, initials: 'ER', timeline: [{ stage: 'Applied', date: '2026-01-14', desc: 'Submitted', status: 'completed' }] },
    { id: 46, opportunityId: 1, candidateId: 45, candidateName: 'Faisal Khan', branch: 'Electronics', cgpa: 7.7, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Interview', appliedDate: '2026-01-20', hasReferral: false, currentStageIndex: 1, initials: 'FK', timeline: [{ stage: 'Applied', date: '2026-01-20', desc: 'Submitted', status: 'completed' }] },
    { id: 47, opportunityId: 1, candidateId: 46, candidateName: 'Yash Bansal', branch: 'IT', cgpa: 8.5, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Offered', appliedDate: '2025-09-10', hasReferral: false, currentStageIndex: 1, initials: 'YB', timeline: [{ stage: 'Applied', date: '2025-09-10', desc: 'Submitted', status: 'completed' }] },
    { id: 48, opportunityId: 8, candidateId: 47, candidateName: 'Ankit Dixit', branch: 'IT', cgpa: 7.6, title: 'Frontend Developer', company: 'WebFlow Media', type: 'Full-Time', status: 'Offered', appliedDate: '2025-09-20', hasReferral: false, currentStageIndex: 1, initials: 'AD', timeline: [{ stage: 'Applied', date: '2025-09-20', desc: 'Submitted', status: 'completed' }] },
    { id: 49, opportunityId: 3, candidateId: 48, candidateName: 'Bhavna Singh', branch: 'IT', cgpa: 8.2, title: 'Full Stack Developer', company: 'InnovateTech', type: 'Full-Time', status: 'Offered', appliedDate: '2025-10-02', hasReferral: false, currentStageIndex: 1, initials: 'BS', timeline: [{ stage: 'Applied', date: '2025-10-02', desc: 'Submitted', status: 'completed' }] },
    { id: 50, opportunityId: 1, candidateId: 49, candidateName: 'Chirag Mehta', branch: 'IT', cgpa: 8.7, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Offered', appliedDate: '2025-10-16', hasReferral: false, currentStageIndex: 1, initials: 'CM', timeline: [{ stage: 'Applied', date: '2025-10-16', desc: 'Submitted', status: 'completed' }] },
    { id: 51, opportunityId: 8, candidateId: 50, candidateName: 'Divya Rao', branch: 'IT', cgpa: 8, title: 'Frontend Developer', company: 'WebFlow Media', type: 'Full-Time', status: 'Offered', appliedDate: '2025-10-24', hasReferral: false, currentStageIndex: 1, initials: 'DR', timeline: [{ stage: 'Applied', date: '2025-10-24', desc: 'Submitted', status: 'completed' }] },
    { id: 52, opportunityId: 3, candidateId: 51, candidateName: 'Esha Goyal', branch: 'IT', cgpa: 7.8, title: 'Full Stack Developer', company: 'InnovateTech', type: 'Full-Time', status: 'Rejected', appliedDate: '2025-11-05', hasReferral: false, currentStageIndex: 1, initials: 'EG', timeline: [{ stage: 'Applied', date: '2025-11-05', desc: 'Submitted', status: 'completed' }] },
    { id: 53, opportunityId: 9, candidateId: 52, candidateName: 'Farida Khan', branch: 'IT', cgpa: 8.4, title: 'Backend Engineer', company: 'FinTech Corp', type: 'Full-Time', status: 'Offered', appliedDate: '2025-11-12', hasReferral: false, currentStageIndex: 1, initials: 'FK', timeline: [{ stage: 'Applied', date: '2025-11-12', desc: 'Submitted', status: 'completed' }] },
    { id: 54, opportunityId: 1, candidateId: 53, candidateName: 'Gaurav Tiwari', branch: 'IT', cgpa: 8.1, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Offered', appliedDate: '2025-11-22', hasReferral: false, currentStageIndex: 1, initials: 'GT', timeline: [{ stage: 'Applied', date: '2025-11-22', desc: 'Submitted', status: 'completed' }] },
    { id: 55, opportunityId: 12, candidateId: 54, candidateName: 'Harshi Patel', branch: 'IT', cgpa: 8.6, title: 'Data Scientist', company: 'DataMinds', type: 'Full-Time', status: 'Offered', appliedDate: '2025-12-05', hasReferral: false, currentStageIndex: 1, initials: 'HP', timeline: [{ stage: 'Applied', date: '2025-12-05', desc: 'Submitted', status: 'completed' }] },
    { id: 56, opportunityId: 8, candidateId: 55, candidateName: 'Iqbal Shaikh', branch: 'IT', cgpa: 7.5, title: 'Frontend Developer', company: 'WebFlow Media', type: 'Full-Time', status: 'Offered', appliedDate: '2025-12-12', hasReferral: false, currentStageIndex: 1, initials: 'IS', timeline: [{ stage: 'Applied', date: '2025-12-12', desc: 'Submitted', status: 'completed' }] },
    { id: 57, opportunityId: 3, candidateId: 56, candidateName: 'Jayant Kumar', branch: 'IT', cgpa: 8.3, title: 'Full Stack Developer', company: 'InnovateTech', type: 'Full-Time', status: 'Offered', appliedDate: '2026-01-05', hasReferral: false, currentStageIndex: 1, initials: 'JK', timeline: [{ stage: 'Applied', date: '2026-01-05', desc: 'Submitted', status: 'completed' }] },
    { id: 58, opportunityId: 1, candidateId: 57, candidateName: 'Kavita Reddy', branch: 'IT', cgpa: 8.9, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Offered', appliedDate: '2026-01-18', hasReferral: false, currentStageIndex: 1, initials: 'KR', timeline: [{ stage: 'Applied', date: '2026-01-18', desc: 'Submitted', status: 'completed' }] },
    { id: 59, opportunityId: 1, candidateId: 58, candidateName: 'Gopal Sharma', branch: 'Electrical', cgpa: 7.9, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Offered', appliedDate: '2025-09-14', hasReferral: false, currentStageIndex: 1, initials: 'GS', timeline: [{ stage: 'Applied', date: '2025-09-14', desc: 'Submitted', status: 'completed' }] },
    { id: 60, opportunityId: 4, candidateId: 59, candidateName: 'Hina Qureshi', branch: 'Electrical', cgpa: 8.1, title: 'ML Engineer', company: 'AI Dynamics', type: 'Full-Time', status: 'Offered', appliedDate: '2025-10-06', hasReferral: false, currentStageIndex: 1, initials: 'HQ', timeline: [{ stage: 'Applied', date: '2025-10-06', desc: 'Submitted', status: 'completed' }] },
    { id: 61, opportunityId: 1, candidateId: 60, candidateName: 'Irfan Shaikh', branch: 'Electrical', cgpa: 7.6, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Rejected', appliedDate: '2025-10-18', hasReferral: false, currentStageIndex: 1, initials: 'IS', timeline: [{ stage: 'Applied', date: '2025-10-18', desc: 'Submitted', status: 'completed' }] },
    { id: 62, opportunityId: 11, candidateId: 61, candidateName: 'Jayesh Patil', branch: 'Electrical', cgpa: 8.3, title: 'Cloud Architect', company: 'Skyline Cloud', type: 'Full-Time', status: 'Offered', appliedDate: '2025-11-07', hasReferral: false, currentStageIndex: 1, initials: 'JP', timeline: [{ stage: 'Applied', date: '2025-11-07', desc: 'Submitted', status: 'completed' }] },
    { id: 63, opportunityId: 1, candidateId: 62, candidateName: 'Kavitha Nair', branch: 'Electrical', cgpa: 7.5, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Offered', appliedDate: '2025-11-15', hasReferral: false, currentStageIndex: 1, initials: 'KN', timeline: [{ stage: 'Applied', date: '2025-11-15', desc: 'Submitted', status: 'completed' }] },
    { id: 64, opportunityId: 9, candidateId: 63, candidateName: 'Lalit Kumar', branch: 'Electrical', cgpa: 8, title: 'Backend Engineer', company: 'FinTech Corp', type: 'Full-Time', status: 'Offered', appliedDate: '2025-12-02', hasReferral: false, currentStageIndex: 1, initials: 'LK', timeline: [{ stage: 'Applied', date: '2025-12-02', desc: 'Submitted', status: 'completed' }] },
    { id: 65, opportunityId: 1, candidateId: 64, candidateName: 'Manisha Yadav', branch: 'Electrical', cgpa: 7.7, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Interview', appliedDate: '2025-12-14', hasReferral: false, currentStageIndex: 1, initials: 'MY', timeline: [{ stage: 'Applied', date: '2025-12-14', desc: 'Submitted', status: 'completed' }] },
    { id: 66, opportunityId: 4, candidateId: 65, candidateName: 'Naresh Babu', branch: 'Electrical', cgpa: 8.2, title: 'ML Engineer', company: 'AI Dynamics', type: 'Full-Time', status: 'Offered', appliedDate: '2026-01-09', hasReferral: false, currentStageIndex: 1, initials: 'NB', timeline: [{ stage: 'Applied', date: '2026-01-09', desc: 'Submitted', status: 'completed' }] },
    { id: 67, opportunityId: 1, candidateId: 66, candidateName: 'Omkar Desai', branch: 'Electrical', cgpa: 7.8, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Offered', appliedDate: '2026-01-22', hasReferral: false, currentStageIndex: 1, initials: 'OD', timeline: [{ stage: 'Applied', date: '2026-01-22', desc: 'Submitted', status: 'completed' }] },
    { id: 68, opportunityId: 11, candidateId: 67, candidateName: 'Padma Rao', branch: 'Electrical', cgpa: 8.5, title: 'Cloud Architect', company: 'Skyline Cloud', type: 'Full-Time', status: 'Offered', appliedDate: '2026-02-05', hasReferral: false, currentStageIndex: 1, initials: 'PR', timeline: [{ stage: 'Applied', date: '2026-02-05', desc: 'Submitted', status: 'completed' }] },
    { id: 69, opportunityId: 1, candidateId: 68, candidateName: 'Omkar Joshi', branch: 'Mechanical', cgpa: 7.8, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Offered', appliedDate: '2025-09-16', hasReferral: false, currentStageIndex: 1, initials: 'OJ', timeline: [{ stage: 'Applied', date: '2025-09-16', desc: 'Submitted', status: 'completed' }] },
    { id: 70, opportunityId: 9, candidateId: 69, candidateName: 'Pradeep Kumar', branch: 'Mechanical', cgpa: 8, title: 'Backend Engineer', company: 'FinTech Corp', type: 'Full-Time', status: 'Offered', appliedDate: '2025-10-10', hasReferral: false, currentStageIndex: 1, initials: 'PK', timeline: [{ stage: 'Applied', date: '2025-10-10', desc: 'Submitted', status: 'completed' }] },
    { id: 71, opportunityId: 1, candidateId: 70, candidateName: 'Ramesh Nair', branch: 'Mechanical', cgpa: 7.5, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Rejected', appliedDate: '2025-10-26', hasReferral: false, currentStageIndex: 1, initials: 'RN', timeline: [{ stage: 'Applied', date: '2025-10-26', desc: 'Submitted', status: 'completed' }] },
    { id: 72, opportunityId: 4, candidateId: 71, candidateName: 'Sunita Reddy', branch: 'Mechanical', cgpa: 7.9, title: 'ML Engineer', company: 'AI Dynamics', type: 'Full-Time', status: 'Offered', appliedDate: '2025-11-20', hasReferral: false, currentStageIndex: 1, initials: 'SR', timeline: [{ stage: 'Applied', date: '2025-11-20', desc: 'Submitted', status: 'completed' }] },
    { id: 73, opportunityId: 3, candidateId: 72, candidateName: 'Trilok Singh', branch: 'Mechanical', cgpa: 8.2, title: 'Full Stack Developer', company: 'InnovateTech', type: 'Full-Time', status: 'Offered', appliedDate: '2025-12-08', hasReferral: false, currentStageIndex: 1, initials: 'TS', timeline: [{ stage: 'Applied', date: '2025-12-08', desc: 'Submitted', status: 'completed' }] },
    { id: 74, opportunityId: 1, candidateId: 73, candidateName: 'Uma Shankar', branch: 'Mechanical', cgpa: 7.3, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Rejected', appliedDate: '2025-12-18', hasReferral: false, currentStageIndex: 1, initials: 'US', timeline: [{ stage: 'Applied', date: '2025-12-18', desc: 'Submitted', status: 'completed' }] },
    { id: 75, opportunityId: 9, candidateId: 74, candidateName: 'Varun Malhotra', branch: 'Mechanical', cgpa: 7.6, title: 'Backend Engineer', company: 'FinTech Corp', type: 'Full-Time', status: 'Offered', appliedDate: '2026-01-12', hasReferral: false, currentStageIndex: 1, initials: 'VM', timeline: [{ stage: 'Applied', date: '2026-01-12', desc: 'Submitted', status: 'completed' }] },
    { id: 76, opportunityId: 1, candidateId: 75, candidateName: 'Piyush Agarwal', branch: 'Mechanical', cgpa: 8.1, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Offered', appliedDate: '2026-01-25', hasReferral: false, currentStageIndex: 1, initials: 'PA', timeline: [{ stage: 'Applied', date: '2026-01-25', desc: 'Submitted', status: 'completed' }] },
    { id: 77, opportunityId: 4, candidateId: 76, candidateName: 'Reena Mishra', branch: 'Mechanical', cgpa: 7.7, title: 'ML Engineer', company: 'AI Dynamics', type: 'Full-Time', status: 'Offered', appliedDate: '2026-02-08', hasReferral: false, currentStageIndex: 1, initials: 'RM', timeline: [{ stage: 'Applied', date: '2026-02-08', desc: 'Submitted', status: 'completed' }] },
    { id: 78, opportunityId: 1, candidateId: 77, candidateName: 'Sachin Verma', branch: 'Mechanical', cgpa: 7.4, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Interview', appliedDate: '2026-02-14', hasReferral: false, currentStageIndex: 1, initials: 'SV', timeline: [{ stage: 'Applied', date: '2026-02-14', desc: 'Submitted', status: 'completed' }] },
    { id: 79, opportunityId: 1, candidateId: 78, candidateName: 'Tina Shah', branch: 'Civil', cgpa: 7.8, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Offered', appliedDate: '2025-10-15', hasReferral: false, currentStageIndex: 1, initials: 'TS', timeline: [{ stage: 'Applied', date: '2025-10-15', desc: 'Submitted', status: 'completed' }] },
    { id: 80, opportunityId: 9, candidateId: 79, candidateName: 'Ujwal Rao', branch: 'Civil', cgpa: 8, title: 'Backend Engineer', company: 'FinTech Corp', type: 'Full-Time', status: 'Offered', appliedDate: '2025-11-08', hasReferral: false, currentStageIndex: 1, initials: 'UR', timeline: [{ stage: 'Applied', date: '2025-11-08', desc: 'Submitted', status: 'completed' }] },
    { id: 81, opportunityId: 1, candidateId: 80, candidateName: 'Vanshika Kapoor', branch: 'Civil', cgpa: 7.2, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Rejected', appliedDate: '2025-11-24', hasReferral: false, currentStageIndex: 1, initials: 'VK', timeline: [{ stage: 'Applied', date: '2025-11-24', desc: 'Submitted', status: 'completed' }] },
    { id: 82, opportunityId: 3, candidateId: 81, candidateName: 'Waqas Ali', branch: 'Civil', cgpa: 7.6, title: 'Full Stack Developer', company: 'InnovateTech', type: 'Full-Time', status: 'Offered', appliedDate: '2025-12-10', hasReferral: false, currentStageIndex: 1, initials: 'WA', timeline: [{ stage: 'Applied', date: '2025-12-10', desc: 'Submitted', status: 'completed' }] },
    { id: 83, opportunityId: 1, candidateId: 82, candidateName: 'Yuvraj Shetty', branch: 'Civil', cgpa: 7.9, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Offered', appliedDate: '2026-01-08', hasReferral: false, currentStageIndex: 1, initials: 'YS', timeline: [{ stage: 'Applied', date: '2026-01-08', desc: 'Submitted', status: 'completed' }] },
    { id: 84, opportunityId: 1, candidateId: 83, candidateName: 'Zain Siddiqui', branch: 'Civil', cgpa: 7.4, title: 'Software Engineer', company: 'TechCorp Solutions', type: 'Full-Time', status: 'Rejected', appliedDate: '2026-01-20', hasReferral: false, currentStageIndex: 1, initials: 'ZS', timeline: [{ stage: 'Applied', date: '2026-01-20', desc: 'Submitted', status: 'completed' }] },
    { id: 85, opportunityId: 9, candidateId: 84, candidateName: 'Anisha Kapoor', branch: 'Civil', cgpa: 8.1, title: 'Backend Engineer', company: 'FinTech Corp', type: 'Full-Time', status: 'Offered', appliedDate: '2026-02-10', hasReferral: false, currentStageIndex: 1, initials: 'AK', timeline: [{ stage: 'Applied', date: '2026-02-10', desc: 'Submitted', status: 'completed' }] },
    { id: 86, opportunityId: 3, candidateId: 85, candidateName: 'Bharat Nair', branch: 'Civil', cgpa: 7.5, title: 'Full Stack Developer', company: 'InnovateTech', type: 'Full-Time', status: 'Offered', appliedDate: '2026-02-18', hasReferral: false, currentStageIndex: 1, initials: 'BN', timeline: [{ stage: 'Applied', date: '2026-02-18', desc: 'Submitted', status: 'completed' }] },
    // ── Google applications — visible to Priya Kapoor (r@gmail.com) ────────────
    { id: 87, opportunityId: 16, candidateId: 2, candidateName: 'Arjun Sharma', branch: 'Computer Science', cgpa: 9.2, title: 'Software Engineer', company: 'Google', type: 'Full-Time', status: 'Shortlisted', appliedDate: '2026-04-02', hasReferral: false, currentStageIndex: 2, initials: 'AS', resumeFile: 'arjun_sharma_resume.pdf', rounds: { resume: 'Pass', assessment: 'Scheduled', technical: 'Scheduled', hr: 'Scheduled' }, timeline: [{ stage: 'Applied', date: '2026-04-02', desc: 'Application received', status: 'completed' }, { stage: 'Shortlisted', date: '2026-04-08', desc: 'Resume matched criteria', status: 'active' }] },
    { id: 88, opportunityId: 16, candidateId: 3, candidateName: 'Priya Patel', branch: 'Electronics & Communication', cgpa: 8.5, title: 'Software Engineer', company: 'Google', type: 'Full-Time', status: 'Interview', appliedDate: '2026-04-03', hasReferral: true, currentStageIndex: 3, initials: 'PP', resumeFile: 'priya_patel_resume.pdf', rounds: { resume: 'Pass', assessment: 'Pass', technical: 'Scheduled', hr: 'Scheduled' }, timeline: [{ stage: 'Applied', date: '2026-04-03', desc: 'Application received', status: 'completed' }, { stage: 'Shortlisted', date: '2026-04-09', desc: 'Resume selected', status: 'completed' }, { stage: 'Interview', date: '2026-04-18', desc: 'Technical round 1 scheduled', status: 'active' }] },
    { id: 89, opportunityId: 16, candidateId: 4, candidateName: 'Rahul Mehta', branch: 'Computer Science', cgpa: 9.1, title: 'Software Engineer', company: 'Google', type: 'Full-Time', status: 'Offered', appliedDate: '2026-03-28', hasReferral: false, currentStageIndex: 4, initials: 'RM', resumeFile: 'rahul_mehta_resume.pdf', rounds: { resume: 'Pass', assessment: 'Pass', technical: 'Pass', hr: 'Pass' }, timeline: [{ stage: 'Applied', date: '2026-03-28', desc: 'Application received', status: 'completed' }, { stage: 'Shortlisted', date: '2026-04-02', desc: 'Resume selected', status: 'completed' }, { stage: 'Interview', date: '2026-04-10', desc: 'All rounds cleared', status: 'completed' }, { stage: 'Offered', date: '2026-04-20', desc: 'Offer letter sent — accept by May 5th', status: 'completed' }] },
    { id: 90, opportunityId: 16, candidateId: 5, candidateName: 'Sneha Reddy', branch: 'Information Technology', cgpa: 8.3, title: 'Software Engineer', company: 'Google', type: 'Full-Time', status: 'Applied', appliedDate: '2026-04-10', hasReferral: false, currentStageIndex: 1, initials: 'SR', resumeFile: 'sneha_reddy_resume.pdf', rounds: { resume: 'Scheduled', assessment: 'Scheduled', technical: 'Scheduled', hr: 'Scheduled' }, timeline: [{ stage: 'Applied', date: '2026-04-10', desc: 'Application received, under review', status: 'completed' }] },
    { id: 91, opportunityId: 17, candidateId: 6, candidateName: 'Vikram Singh', branch: 'Computer Science', cgpa: 8.7, title: 'Site Reliability Engineer', company: 'Google', type: 'Full-Time', status: 'Applied', appliedDate: '2026-04-12', hasReferral: false, currentStageIndex: 1, initials: 'VS', resumeFile: 'vikram_singh_resume.pdf', rounds: { resume: 'Scheduled', assessment: 'Scheduled', technical: 'Scheduled', hr: 'Scheduled' }, timeline: [{ stage: 'Applied', date: '2026-04-12', desc: 'Application received, under review', status: 'completed' }] },
  ];

  private nextId = 92;


  findAll(): Application[] {
    return this.applications;
  }

  findByCandidate(candidateId: number): Application[] {
    return this.applications.filter((a) => a.candidateId === candidateId);
  }

  findByOpportunity(opportunityId: number): Application[] {
    return this.applications.filter((a) => a.opportunityId === opportunityId);
  }

  findById(id: number): Application | undefined {
    return this.applications.find((a) => a.id === id);
  }

  existsByOpportunityAndCandidate(opportunityId: number, candidateId: number): boolean {
    return this.applications.some(
      (a) => a.opportunityId === opportunityId && a.candidateId === candidateId,
    );
  }

  findByCollege(collegeId: number): Application[] {
    return this.applications.filter(a => a.collegeId === collegeId);
  }

  create(data: Omit<Application, 'id'>): Application {
    const app: Application = { id: this.nextId++, ...data };
    this.applications.push(app);
    return app;
  }

  update(id: number, data: Partial<Application>): Application | undefined {
    const idx = this.applications.findIndex((a) => a.id === id);
    if (idx === -1) return undefined;
    this.applications[idx] = { ...this.applications[idx], ...data };
    return this.applications[idx];
  }

  remove(id: number): boolean {
    const idx = this.applications.findIndex((a) => a.id === id);
    if (idx === -1) return false;
    this.applications.splice(idx, 1);
    return true;
  }
}

